apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: codefresh-eventbus
spec:
  nats:
    native:
      maxBytes: "200MB"
#       maxPayload: "2MB"
#       raftHeartbeatTimeout: "10s"
#       raftElectionTimeout: "10s"
#       raftCommitTimeout: "7s"
#       raftLeaseTimeout: "3s"
#       containerTemplate:
#         resources:
#           limits:
#             cpu: 2
#             memory: 8Gi
#             ephemeral-storage: 2Gi
#           requests:
#             cpu: 1
#             memory: 2Gi
#             ephemeral-storage: 2Gi
